server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/productdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update

  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
